name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Preprocessing
        run: python scripts/data_preprocessing.py

      - name: Train Model
        run: python scripts/train_model.py --model random_forest

      - name: Run API Tests (Optional)
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -X 'POST' 'http://127.0.0.1:8000/predict' \
          -H 'Content-Type: application/json' \
          -d '{"Age": 30, "Salary": 60000, "Department": 2}'
