name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ✅
        uses: actions/checkout@v3

      - name: Set Up Python ✅
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Required Build Tools ✅
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Dependencies ✅
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            cat requirements.txt  # Debugging step
            pip install -r requirements.txt
          else
            echo "❌ requirements.txt NOT FOUND"; exit 1
          fi

      - name: Debug - Check File Structure ✅
        run: ls -R  # This lists all files in the project to verify paths

      - name: Run Data Preprocessing ✅
        run: |
          if [ -f scripts/data_preprocessing.py ]; then
            python scripts/data_preprocessing.py
          else
            echo "❌ scripts/data_preprocessing.py NOT FOUND"; exit 1;
          fi

      - name: Train Model ✅
        run: |
          if [ -f scripts/train_model.py ]; then
            python scripts/train_model.py --model random_forest
          else
            echo "❌ scripts/train_model.py NOT FOUND"; exit 1;
          fi

      - name: Run API Tests (Optional) ✅
        run: |
          if ! pip show fastapi uvicorn > /dev/null; then
            echo "❌ FastAPI or Uvicorn NOT INSTALLED"; exit 1;
          fi
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &  # Start FastAPI server
          sleep 5  # Wait for the server to start
          curl -X 'POST' 'http://127.0.0.1:8000/predict' \
          -H 'Content-Type: application/json' \
          -d '{"Age": 30, "Salary": 60000, "Department": 2}'
